#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

application:
  id: w20-bridge-sample
  name: W20 bridge sample

rest: /api

security:
  users:
    demo: demo
  web:
    urls:
#      -
#        pattern: /**
#        filters: authcBasic

sample:
  defaultName: World
