#
# Copyright Â© 2013-2018, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

version: "2"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  app:
    image: org.seedstack.samples/ddd-sample
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://db:27017/${DB_NAME}
